---
strix_halo_image: "docker.io/kyuz0/vllm-therock-gfx1151:latest"
strix_halo_toolbox_name: "vllm"
strix_halo_target_user: "{{ ansible_user_id }}"
strix_halo_require_devices: true
strix_halo_devices:
  - /dev/dri
  - /dev/kfd
strix_halo_groups:
  - video
  - render
strix_halo_security_opt_seccomp_unconfined: true
strix_halo_rdma_enabled: false
strix_halo_rdma_device_path: "/dev/infiniband"
