---
strix_halo_mode: "toolbox"
strix_halo_toolbox_name: "vllm"
strix_halo_target_user: "{{ ansible_user_id }}"
strix_halo_devices:
  - /dev/dri
  - /dev/kfd
strix_halo_groups:
  - video
  - render
vllm_enabled: false
vllm_port: 8000
vllm_api_key_enabled: true
vllm_api_key_value: "local-dev-key"
vllm_container_name: "vllm-server"
ui_enabled: false
openwebui_port: 3000
openwebui_container_name: "open-webui"
verify_log_lines: 50
